name: Test
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '--cfg getrandom_backend="wasm_js"'

jobs:
  cargo:
    name: Test
    runs-on: codeberg-medium
    steps:
      - uses: actions/checkout@v6
      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: curl https://wasm-bindgen.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: cargo fmt --check
      - run: wasm-pack test --chrome --chromedriver "$(which chromedriver)" --headless
        working-directory: ./lib

  clippy:
    name: Lint
    runs-on: codeberg-medium
    if: forgejo.ref_type != 'tag'
    steps:
      - uses: actions/checkout@v6
      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: wasm32-unknown-unknown
      - run: cargo clippy --target wasm32-unknown-unknown --all-features -- -D clippy::all -D warnings

  publish:
    needs: cargo
    name: Publish
    runs-on: codeberg-medium
    if: forgejo.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v6
      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - run: cargo publish --target wasm32-unknown-unknown -p webpixels --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
