[package]
name = "pixelmosh-w3"
version = "0.1.0-alpha"
authors = ["charlesrocket"]
edition = "2021"
categories = ["wasm"]

[dependencies]
console_log = "~0.2"
log = "~0.4"
seed = "~0.9"
webpixels = { path = "../lib" }
