[package]
publish = false
name = "pixelmosh-w3"
version = "0.1.0-alpha"
authors = ["charlesrocket"]
edition = "2021"
categories = ["wasm"]

[dependencies]
seed = "0.10"
gloo-console = "0.3"
webpixels = { path = "../lib" }
