[package]
name = "pixelmosh-w3"
version = "0.1.0"
authors = ["charlesrocket"]
edition = "2021"
categories = ["wasm"]

[dependencies]
console_log = "~0.2"
log = "~0.4"
sycamore = "0.8.0-beta.7"
webpixels = { path = "../lib" }
