name: deploy

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: swatinem/rust-cache@v1
      - name: Install dependencies
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make
      - name: Build
        run: cargo make build_release
        working-directory: ./www
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
