name: Deploy
on: push

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '--cfg getrandom_backend="wasm_js"'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add wasm32-unknown-unknown
      - name: Install trunk
        uses: jetli/trunk-action@v0.5.1
        with:
          version: "latest"
      - name: Build
        run: trunk build --release --public-url https://charlesrocket.github.io/webpixels/
        working-directory: ./www
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./www/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
